export const LOAD_QUESTION_CATEGORIES = 'LOAD_QUESTION_CATEGORIES';
export const LOAD_QUESTION_CATEGORIES_SUCCESS = 'LOAD_QUESTION_CATEGORIES_SUCCESS';
export const LOAD_QUESTION_CATEGORIES_FAILURE = 'LOAD_QUESTION_CATEGORIES_FAILURE';
export const CREATE_QUESTION_CATEGORY = 'CREATE_QUESTION_CATEGORY';
export const CREATE_QUESTION_CATEGORY_SUCCESS = 'CREATE_QUESTION_CATEGORY_SUCCESS';
export const CREATE_QUESTION_CATEGORY_FAILURE = 'CREATE_QUESTION_CATEGORY_FAILURE';
export const UPDATE_QUESTION_CATEGORY = 'UPDATE_QUESTION_CATEGORY';
export const UPDATE_QUESTION_CATEGORY_SUCCESS = 'UPDATE_QUESTION_CATEGORY_SUCCESS';
export const UPDATE_QUESTION_CATEGORY_FAILURE = 'UPDATE_QUESTION_CATEGORY_FAILURE';
export const DELETE_QUESTION_CATEGORY = 'DELETE_QUESTION_CATEGORY';
export const DELETE_QUESTION_CATEGORY_SUCCESS = 'DELETE_QUESTION_CATEGORY_SUCCESS';
export const DELETE_QUESTION_CATEGORY_FAILURE  = 'DELETE_QUESTION_CATEGORY_FAILURE';

export const LOAD_COURSE_CATEGORIES = 'LOAD_COURSE_CATEGORIES';
export const LOAD_COURSE_CATEGORIES_SUCCESS = 'LOAD_COURSE_CATEGORIES_SUCCESS';
export const LOAD_COURSE_CATEGORIES_FAILURE = 'LOAD_COURSE_CATEGORIES_FAILURE';
export const CREATE_COURSE_CATEGORY = 'CREATE_COURSE_CATEGORY';
export const CREATE_COURSE_CATEGORY_SUCCESS = 'CREATE_COURSE_CATEGORY_SUCCESS';
export const CREATE_COURSE_CATEGORY_FAILURE = 'CREATE_COURSE_CATEGORY_FAILURE';
export const UPDATE_COURSE_CATEGORY = 'UPDATE_COURSE_CATEGORY';
export const UPDATE_COURSE_CATEGORY_SUCCESS = 'UPDATE_COURSE_CATEGORY_SUCCESS';
export const UPDATE_COURSE_CATEGORY_FAILURE = 'UPDATE_COURSE_CATEGORY_FAILURE';
export const DELETE_COURSE_CATEGORY = 'DELETE_COURSE_CATEGORY';
export const DELETE_COURSE_CATEGORY_SUCCESS = 'DELETE_COURSE_CATEGORY_SUCCESS';
export const DELETE_COURSE_CATEGORY_FAILURE  = 'DELETE_COURSE_CATEGORY_FAILURE';

export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE  = 'DELETE_USER_FAILURE';

export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILURE = 'LOAD_QUESTIONS_FAILURE';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE  = 'DELETE_QUESTION_FAILURE';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_FAILURE  = 'UPDATE_QUESTION_FAILURE';
export const LOAD_SINGLE_QUESTION = 'LOAD_SINGLE_QUESTION';
export const LOAD_SINGLE_QUESTION_SUCCESS = 'LOAD_SINGLE_QUESTION_SUCCESS';
export const LOAD_SINGLE_QUESTION_FAILURE = 'LOAD_SINGLE_QUESTION_FAILURE';

export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAILURE = 'LOAD_COURSES_FAILURE';

export const LOAD_SINGLE_COURSE = 'LOAD_SINGLE_COURSE';
export const LOAD_SINGLE_COURSE_SUCCESS = 'LOAD_SINGLE_COURSE_SUCCESS';
export const LOAD_SINGLE_COURSE_FAILURE = 'LOAD_SINGLE_COURSE_FAILURE';

export const LOAD_USER_COURSES = 'LOAD_USER_COURSES';
export const LOAD_USER_COURSES_SUCCESS = 'LOAD_USER_COURSES_SUCCESS';
export const LOAD_USER_COURSES_FAILURE = 'LOAD_USER_COURSES_FAILURE';

export const LOAD_INSTRUCTOR_COURSES = 'LOAD_INSTRUCTOR_COURSES';
export const LOAD_INSTRUCTOR_COURSES_SUCCESS = 'LOAD_INSTRUCTOR_COURSES_SUCCESS';
export const LOAD_INSTRUCTOR_COURSES_FAILURE = 'LOAD_INSTRUCTOR_COURSES_FAILURE';

export const CREATE_ONE_QUESTION_PER_PAGE_QUIZ = 'CREATE_ONE_QUESTION_PER_PAGE_QUIZ';
export const CREATE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS = 'CREATE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS';
export const CREATE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE = 'CREATE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE';

export const UPDATE_ONE_QUESTION_PER_PAGE_QUIZ = 'UPDATE_ONE_QUESTION_PER_PAGE_QUIZ';
export const UPDATE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS = 'UPDATE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS';
export const UPDATE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE = 'UPDATE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE';

export const DELETE_ONE_QUESTION_PER_PAGE_QUIZ = 'DELETE_ONE_QUESTION_PER_PAGE_QUIZ';
export const DELETE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS = 'DELETE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS';
export const DELETE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE = 'DELETE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE';

export const LOAD_ONE_QUESTION_PER_PAGE_QUIZZES = 'LOAD_ONE_QUESTION_PER_PAGE_QUIZZES';
export const LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_SUCCESS = 'LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_SUCCESS';
export const LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_FAILURE = 'LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_FAILURE';

export const LOAD_SINGLE_ONE_QUESTION_PER_PAGE_QUIZ = 'LOAD_SINGLE_ONE_QUESTION_PER_PAGE_QUIZ';
export const LOAD_SINGLE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS = 'LOAD_SINGLE_ONE_QUESTION_PER_PAGE_QUIZ_SUCCESS';
export const LOAD_SINGLE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE = 'LOAD_SINGLE_ONE_QUESTION_PER_PAGE_QUIZ_FAILURE';

export const LOAD_COURSE_CATEGORIES_OPTIONS_HTML = 'LOAD_COURSE_CATEGORIES_OPTIONS_HTML';
export const LOAD_COURSE_CATEGORIES_OPTIONS_HTML_SUCCESS = 'LOAD_COURSE_CATEGORIES_OPTIONS_HTML_SUCCESS';
export const LOAD_COURSE_CATEGORIES_OPTIONS_HTML_FAILURE = 'LOAD_COURSE_CATEGORIES_OPTIONS_HTML_FAILURE';

export const LOAD_QUESTION_CATEGORIES_OPTIONS_HTML = 'LOAD_QUESTION_CATEGORIES_OPTIONS_HTML';
export const LOAD_QUESTION_CATEGORIES_OPTIONS_HTML_SUCCESS = 'LOAD_QUESTION_CATEGORIES_OPTIONS_HTML_SUCCESS';
export const LOAD_QUESTION_CATEGORIES_OPTIONS_HTML_FAILURE = 'LOAD_QUESTION_CATEGORIES_OPTIONS_HTML_FAILURE';

export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_INSTRUCTOR_PROFILE_SUCCESS = 'UPDATE_INSTRUCTOR_PROFILE_SUCCESS';

export const USER_LOAD_ONE_QUESTION_PER_PAGE_QUIZZES = 'USER_LOAD_ONE_QUESTION_PER_PAGE_QUIZZES';
export const USER_LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_SUCCESS = 'USER_LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_SUCCESS';
export const USER_LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_FAILURE = 'USER_LOAD_ONE_QUESTION_PER_PAGE_QUIZZES_FAILURE';

export const LOAD_USER_TRANSACTIONS = 'LOAD_USER_TRANSACTIONS';
export const LOAD_USER_TRANSACTIONS_SUCCESS = 'LOAD_USER_TRANSACTIONS_SUCCESS';
export const LOAD_USER_TRANSACTIONS_FAILURE = 'LOAD_USER_TRANSACTIONS_FAILURE';

export const LOAD_USER_DETAIL_TRANSACTIONS = 'LOAD_USER_DETAIL_TRANSACTIONS';
export const LOAD_USER_DETAIL_TRANSACTIONS_SUCCESS = 'LOAD_USER_DETAIL_TRANSACTIONS_SUCCESS';
export const LOAD_USER_DETAIL_TRANSACTIONS_FAILURE = 'LOAD_USER_DETAIL_TRANSACTIONS_FAILURE';

export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const UPDATE_COURSE_CURRICULUM = 'UPDATE_COURSE_CURRICULUM';
export const UPDATE_COURSE_CURRICULUM_SUCCESS = 'UPDATE_COURSE_CURRICULUM_SUCCESS';
export const UPDATE_COURSE_CURRICULUM_FAILURE = 'UPDATE_COURSE_CURRICULUM_FAILURE';

export const LOAD_COURSE_CURRICULUM = 'LOAD_COURSE_CURRICULUM';
export const LOAD_COURSE_CURRICULUM_SUCCESS = 'LOAD_COURSE_CURRICULUM_SUCCESS';
export const LOAD_COURSE_CURRICULUM_FAILURE = 'LOAD_COURSE_CURRICULUM_FAILURE';

export const LOAD_LESSION_BY_LESSION_ID = 'LOAD_LESSION_BY_LESSION_ID';
export const LOAD_LESSION_BY_LESSION_ID_SUCCESS = 'LOAD_LESSION_BY_LESSION_ID_SUCCESS';
export const LOAD_LESSION_BY_LESSION_ID_FAILURE = 'LOAD_LESSION_BY_LESSION_ID_FAILURE';

export const ADD_COURSE_TO_CART = 'ADD_COURSE_TO_CART';
export const ADD_COURSE_TO_CART_SUCCESS = 'ADD_COURSE_TO_CART_SUCCESS';
export const ADD_COURSE_TO_CART_FAILURE = 'ADD_COURSE_TO_CART_FAILURE';

export const REMOVE_COURSE_FROM_CART = 'REMOVE_COURSE_FROM_CART';
export const REMOVE_COURSE_FROM_CART_SUCCESS = 'REMOVE_COURSE_FROM_CART_SUCCESS';
export const REMOVE_COURSE_FROM_CART_FAILURE = 'REMOVE_COURSE_FROM_CART_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const BECOME_AN_INSTRUCTOR = 'BECOME_AN_INSTRUCTOR';
export const BECOME_AN_INSTRUCTOR_SUCCESS = 'BECOME_AN_INSTRUCTOR_SUCCESS';
export const BECOME_AN_INSTRUCTOR_FAILURE = 'BECOME_AN_INSTRUCTOR_FAILURE';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOAD_AUTHENTICATED_USER = 'LOAD_AUTHENTICATED_USER';
export const LOAD_AUTHENTICATED_USER_SUCCESS = 'LOAD_AUTHENTICATED_USER_SUCCESS';
export const LOAD_AUTHENTICATED_USER_FAILURE = 'LOAD_AUTHENTICATED_USER_FAILURE';

export const LOAD_MULTIPLE_COURSES = 'LOAD_MULTIPLE_COURSES';
export const LOAD_MULTIPLE_COURSES_SUCCESS = 'LOAD_MULTIPLE_COURSES_SUCCESS';
export const LOAD_MULTIPLE_COURSES_FAILURE = 'LOAD_MULTIPLE_COURSES_FAILURE';